const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  primarySidebar: [{ type: "autogenerated", dirName: "." }],
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
